[colors-dark]
alpha=0.35
background=434141
foreground=ffffff
regular0=434141
regular1=8C8075
regular2=9A9087
regular3=A8A19A
regular4=B8AEA3
regular5=C5BBB4
regular6=E2DDD9
regular7=ACA59E
bright0=78736E
bright1=8C8075
bright2=9A9087
bright3=A8A19A
bright4=B8AEA3
bright5=C5BBB4
bright6=E2DDD9
bright7=ACA59E
cursor=ffffff 434141

[colors-light]
alpha=0.35
background=434141
foreground=ffffff
regular0=434141
regular1=8C8075
regular2=9A9087
regular3=A8A19A
regular4=B8AEA3
regular5=C5BBB4
regular6=E2DDD9
regular7=ACA59E
bright0=78736E
bright1=8C8075
bright2=9A9087
bright3=A8A19A
bright4=B8AEA3
bright5=C5BBB4
bright6=E2DDD9
bright7=ACA59E
cursor=ffffff 434141

[cursor]
# style, blink, etc. can stay here
